### ISSUE TITLE
Failed to start realtime transcribe only on real device (IOS)

### ISSUE THREAD

**Issue by EmanuelCampos** [mybigday/whisper.rn#104]
Hello guys, I was running the project on the Simulator and it's working well, then when I was going to play on my device it tried to download coreML and crashed with an error

whisper_init_state: loading Core ML model from '/var/mobile/Containers/Data/Application/65C6185E-FE0C-4F8E-92B5-8F06976A2A66/Documents/whisper/ggml-tiny.en-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: failed to load Core ML model from '/var/mobile/Containers/Data/Application/65C6185E-FE0C-4F8E-92B5-8F06976A2A66/Documents/whisper/ggml-tiny.en-encoder.mlmodelc'
2023-08-24 10:23:58.429128-0300 app-name[12099:2597258] [native] SocketRocket: In debug mode.  Allowing connection to any root cert
2023-08-24 10:23:58.552915-0300 app-name[12099:2597544] [javascript] 'Failed to start recording', [Error: Failed to start realtime transcribe. Status: 561145187]
2023-08-24 10:23:58.556127-0300 app-name[12099:2597258] [native] JSON value '{
    code = "whisper_error";
    domain = RCTErrorDomain;
    jsEngine = hermes;
    message = "Failed to start realtime transcribe. Status: 561145187";
    
 **EDIT 1:** I was able to download the coreML models, and isn't having more the failed to load, but still have this error, appears something with the audio playing in background, but I already set the permissions
 
  **EDIT 2:** To record on IOS + expo I'm having to use expo-av to record, then start the transcribe realtime after it, still investigating

**Comment by jhen0409** [comment]
I think we should start an AVAudioSesssion before AudioQueueNewInput, with the `AVAudioSessionCategoryOptionMixWithOthers` category.

**Comment by jhen0409** [comment]
We may implement the AVAudioSesssion API into whisper.rn later.

Currently [react-native-audio-session](https://github.com/BonnierNews/react-native-audio-session) might be a good option to control the audio session.

**Comment by EmanuelCampos** [comment]
I had another issue together, not sure if it's related, The audio is always enabled in background (I enabled the background option on IOS to play audio)

![image](https://github.com/mybigday/whisper.rn/assets/16262455/66960c75-73b0-498b-b66b-d4ab00309885)

**Comment by JEF1056** [comment]
Adding on to this: I'm having issues with both a real IPad (M1) and the IOS Simulator Ipad
In the real Ipad, I get `Failed to start realtime transcribe. Status: 561145187`
On the simulated Ipad, I get `Failed to start realtime transcribe. Status: -66628`

I've attempted to use `react-native-audio session`, setting mode and category like this:
```
await AudioSession.setCategory("Record", "MixWithOthers");
await AudioSession.setMode("SpokenAudio");
await AudioSession.setActive(true);
```
Which stops the errors, but now realtimeTranscribe() doesn't record any audio. The output .wav file is <1 second.
In Xcode I can see the below logs on the simulator:
```
HALSystem.cpp:2,216  AudioObjectPropertiesChanged: no such object
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
AQMEIO_HAL.cpp:2,485 timeout
AudioHardware-mac-imp.cpp:2,706  AudioDeviceStop: no device with given ID
AudioHardware-mac-imp.cpp:2,866  AudioDeviceGetCurrentTime: no device with given ID
[RNWhisper] Slice 0 has 0 samples
[RNWhisper] Transcribing 7,168 samples
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 122
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 122
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 122
AQMEIO_HAL.cpp:2,706 iOSSimulatorAudioDevice-19902-1: Abandoning I/O cycle because reconfig pending (1).
HALC_ProxySystem.cpp:165  HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560,947,818 (!obj)
HALC_ShellObject.mm:213  HALC_ShellObject::HasProperty: there is no proxy object
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 125
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 125
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 125
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 125
AudioHardware-mac-imp.cpp:1,224  AudioObjectRemovePropertyListener: no object with given ID 125
HALSystem.cpp:2,216  AudioObjectPropertiesChanged: no such object
[RNWhisper] Slice 0 has 7,168 samples
[RNWhisper] Slice 0 has 8,974 samples
[RNWhisper] Slice 0 has 8,974 samples
[RNWhisper] Transcribing 8,974 samples
[RNWhisper] Transcribe end
```

**Comment by jhen0409** [comment]
> I've attempted to use `react-native-audio session`, setting mode and category like this:
> 
> ```
> await AudioSession.setCategory("Record", "MixWithOthers");
> await AudioSession.setMode("SpokenAudio");
> await AudioSession.setActive(true);
> ```
> 
> Which stops the errors, but now realtimeTranscribe() doesn't record any audio. The output .wav file is <1 second.
In Xcode I can see the below logs on the simulator:

I don't have the issue with the code on my iOS 17 device & simulator. I use `PlayAndRecord` because it seems like `Record` is not compatible with the mode.
