### ISSUE TITLE
Releasing whisperContext shortly after you initialise it crashes on iOS

### ISSUE THREAD

**Issue by jobpaardekooper** [mybigday/whisper.rn#107]
The following code:
```
const whisperContext = await initWhisper({ filePath: modelPath })

console.log("Done")
setTimeout(() => {
    console.log("Will crash...")
    whisperContext.release()
}, 1000)
```

Causes a crash on iOS. Here is what I get in Xcode:
![Screenshot 2023-08-25 at 18 40 59](https://github.com/mybigday/whisper.rn/assets/34612663/9e2d5ac1-98f3-4a6d-8748-8a662d9345f1)

**Comment by jhen0409** [comment]
It can be determined that the problem is not in the release after initialize, but in the release in transcribing - the ggml opt is only happened on transcription.

**Comment by jobpaardekooper** [comment]
@jhen0409 Thanks for starting to look into it. I forgot to explicitly stop the transcription in my code example but even when stopping before releasing you get the same crash. For example using the following code:
```ts
const whisperContext = await initWhisper({ filePath: modelPath })
        
const { stop, promise } = whisperContext.transcribe(inputFilePath)

setTimeout(() => {
    console.log("Will crash...")
    stop()
    whisperContext.release()
}, 1000)
```

I think the problem lies in the `stop` function returned by `whisperContext.transcribe(inputFilePath)`. The `stop` function is of type `() => void` but to me it seems like this should be an async function because it is communicating with native and all the other calls to native are async because JSI is not being used right? So the type of `stop` should be `() => Promise<void>`. If that is implemented correctly we should be able to run the following **updated** code snippet without crashing:
```ts
const whisperContext = await initWhisper({ filePath: modelPath })
        
const { stop, promise } = whisperContext.transcribe(inputFilePath)

setTimeout(async () => {
    console.log("Will NOT crash...?")
    await stop()
    await whisperContext.release()
}, 1000)
```

What do you think of this theory @jhen0409?

**Comment by jobpaardekooper** [comment]
Great work, thanks for looking in to it!
