### ISSUE TITLE
not being able to use fork

### ISSUE THREAD

**Issue by EmanuelCampos** [mybigday/whisper.rn#113]
Hello guys, I tried to fork the package because was being impacted by the issue:
[fix(ios): recording not stop on abort](https://github.com/mybigday/whisper.rn/commit/589da4a3c44e1fe8e6ea3bf7f81f7938e9bf1a84)

but when using a fork instead of the npm was having a issue: "whisper.h not found" on xcode, and CMake issues as well, Is missing something on the repo, or any step that I should do?

For now, I applied a patch-package, while I'm waiting the release.

**Comment by jhen0409** [comment]
Currently it requires to run the bootstrap script, so the git repo is not able to used as a npm package directly.

I'm considering to add the native source to git, and I think it has some other benefits as well.
