### ISSUE TITLE
transcribeRealtime: Option to save wav file

### ISSUE THREAD

**Issue by jhen0409** [mybigday/whisper.rn#12]
It can collect the audio samples then, then add RIFF WAVE fmt header and save file on stopped or finished.

**Comment by JEF1056** [comment]
Any update on this? it would be great to be able to access at least tthe audiobuffers after the text has been transcribed

**Comment by jhen0409** [comment]
Not high priority to us, but it does have some benefits. I can do this when I have time.

**Comment by JEF1056** [comment]
@jhen0409 I've made the changes to save an audio file on the android side, but the IOS implementation is a bit beyond me- see https://github.com/JEF1056/whisper.rn/commit/82cd2fe0d345fd581dfbcb2a9af2c4a386725501

If you could add an IOS implementation, that would be great!

**Comment by jhen0409** [comment]
@JEF1056 That's awesome! Will you open a PR? I can implement the iOS part later.

**Comment by JEF1056** [comment]
> @JEF1056 That's awesome! Will you open a PR? I can implement the iOS part later.

Sure thing! I messed up my fork a bit so I'll clean it up and send a PR over.
I need the WAV on IOS functionality by about October 15th, if you could get it done before then that would be great!

**Comment by JEF1056** [comment]
@jhen0409 See this PR https://github.com/mybigday/whisper.rn/pull/128
