### ISSUE TITLE
Cannot read property 'getConstants' of null I am getting this error while using this in Expo

### ISSUE THREAD

**Issue by saridsa1** [mybigday/whisper.rn#131]
I have downloaded the model file to avoid downloading and also included the extensions in the metro.config.js, I am able to see on screen that this issue is with coreMLAllowFallback.

**Comment by jhen0409** [comment]
It's because the RNWhisper native module is not linked, it's not a built-in module in Expo. I recommend to prebuild the expo project or create a development build via eas-cli.

**Comment by IrfanAli17899** [comment]
@jhen0409 i am getting this error even after dev client, the build is successful but still i am getting error
`Cannot read property of getConstants of null`
 "expo": "~53.0.5"
 "whisper.rn": "^0.4.0-rc.12"
