### ISSUE TITLE
Android build failing

### ISSUE THREAD

**Issue by aosasona** [mybigday/whisper.rn#14]
Uhm, I'm not very good at C++ so I am unable to make a PR to fix this but the android build (for dev) keeps failing like this, please help with this? 🙏 

![Screenshot 2023-03-28 at 00 20 24](https://user-images.githubusercontent.com/97124713/228088348-6289ff33-8905-487a-9070-d9f7d01ba1c9.png)

Referenced line: https://github.com/mybigday/whisper.rn/blob/4a6e287551aca2c0180e312aa1cb4ccd65959dde/android/src/main/jni/whisper/jni.cpp#LL64C34-L64C34

**Comment by jhen0409** [comment]
It required to set ndkVersion up to ^24, see the [example](https://github.com/mybigday/whisper.rn/blob/main/example/android/build.gradle#L9).

However, I think it could have a fix to support lower versions of NDK.

**Comment by aosasona** [comment]
Oh heavens, now I have to fiddle with Android studio and hope I don’t break anything else. Thanks a lot! And great work bringing this to mobile devices, you’re a cape-less hero! On 28 Mar 2023, at 00:46, Jhen-Jie Hong ***@***.***> wrote:﻿
It required to set ndkVersion up to ^24, see the example.
However, I think it could have a fix to support lower versions of NDK.

**Comment by jhen0409** [comment]
Sorry, I've tested, the main problem should be `minSdkVersion`, you can set to `23` until the fix.
