### ISSUE TITLE
Unable to stop transcription on android

### ISSUE THREAD

**Issue by jobpaardekooper** [mybigday/whisper.rn#141]
Calling the stop method while a transcription is in progress on android does not actually stop anything. If you await the stop call it will just complete once it is fully done with transcribing. You can also clearly see this problem if you add an on progress like this:

```js
onProgress: (progress => {
    console.log("Current progress:", progress)
}),
``` 

If you call stop you will see that it still continues loggin the percentages until the transcription is done.

**Comment by jhen0409** [comment]
Currently the abort mechanism is to use [`encoder_begin_callback`](https://github.com/ggerganov/whisper.cpp/blob/c76c11e59c65f5fe74aaf9d3951b8770b77b923b/whisper.cpp#L4589), but usually we need to wait for a loop before aborting. Maybe we could add more breakpoints, but that might not be ideal. I feel like it needs to improve its performance for Android to get a better experience.

**Comment by jobpaardekooper** [comment]
Understandable, thanks for the response.

My problem currently is that the user might start a new transcription right after the stopped another one resulting in an OOM kill because the previous one has not been stopped and cleared. But I do not want to keep them stuck waiting a long time while we stop the transcription.

Any good idea to make this a nice user experience?

**Comment by jhen0409** [comment]
https://github.com/ggerganov/whisper.cpp/pull/1335 seems a good solution we can try.

> My problem currently is that the user might start a new transcription right after the stopped another one resulting in an OOM kill because the previous one has not been stopped and cleared.

This looks like a bug we could fix.

**Comment by jobpaardekooper** [comment]
Thanks for getting back so fast. Would be great if you could add that PR you linked.

My issue was not really I bug but maybe I explained it poorly. Because I don't reuse the whisper context between transcripts in my app. That is why it goes OOM. The user might restart a transcript quickly or they might nog transcribe anything for a while. So I don't what to keep the context around. The issue was just that I did not wan't to wait for it to be fully stoped before allowing the user to move on because that was taking such a long time. Would be great to see how it goed when that PR is added.
