### ISSUE TITLE
Set the language to Thai but it returns results in English

### ISSUE THREAD

**Issue by nguyendinhduy13** [mybigday/whisper.rn#153]
![Screenshot 2023-10-26 at 09 38 24](https://github.com/mybigday/whisper.rn/assets/100419544/82b1018f-2795-474f-b996-f488acd7c4c2)

**Comment by jhen0409** [comment]
Which model are you using? Make sure to use a non `.en` model.

**Comment by nguyendinhduy13** [comment]
@jhen0409 I use the code example, and I only modify the 'language' field to 'th'
![Screenshot 2023-10-26 at 17 04 07](https://github.com/mybigday/whisper.rn/assets/100419544/9ae620ee-74cc-4a79-8120-283e84767aa9)

**Comment by nguyendinhduy13** [comment]
@jhen0409 thank you <3,  i fixed it
