### ISSUE TITLE
Sync whisper.cpp for V3 support

### ISSUE THREAD

**Issue by jobpaardekooper** [mybigday/whisper.rn#155]
OpenAI has released a V3 of the whisper models. It seems like whisper.cpp has already added support for it. Can you sync the code again to introduce these new features?

**Comment by jhen0409** [comment]
It should be already in #154, only the `large` model is affected.

**Comment by jobpaardekooper** [comment]
Great! Was looking at the commits before I posted this issue but the GitHub mobile app did not show the new commits yet. Now they are showing.

Thanks for the quick work!
