### ISSUE TITLE
can't run yarn example android

### ISSUE THREAD

**Issue by pksinghus** [mybigday/whisper.rn#265]
I can run `yarn bootstrap` but when I run `yarn example android` the CPU goes in a spin and the app never runs.

```
whisper.rn % yarn --version
3.6.4
whisper.rn % yarn example ios
Usage Error: Couldn't find a script named "ios".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

whisper.rn % yarn example android
^C%
```

**Comment by jhen0409** [comment]
I guess Yarn v3 can't run command for sub folder, so you can run command like `cd example && yarn ios` instead.

Currently we still using Yarn v1 in this project. I'll support latest version of Yarn in the future if needed.
