### ISSUE TITLE
Failed to initialize Whisper: [java.lang.Exception: Failed to initialize context]

### ISSUE THREAD

**Issue by Wali-Shajeeh** [mybigday/whisper.rn#270]
useEffect(() => {
    const initializeWhisper = async () => {
      try {
        console.log("Starting Whisper initialization...");
        const context = await initWhisper({
          filePath: 'file://.../ggml-tiny.en.bin',
        });
        setWhisperContext(context);
        console.log("Whisper initialized successfully");
      } catch (error) {
        console.error("Failed to initialize Whisper:", error);
      }
    };
    
 used this and my assets folder is in main app directory which contains ggml-tiny.en.bin
 I change several file path types but can not implement this. Can you help me out. I have very short deadline
thanks

**Comment by jhen0409** [comment]
If you're use an asset, make sure you use `require` instead of a file path:

https://github.com/mybigday/whisper.rn/blob/92b9a2517c87587f48f57d7b4f1eb95aeddd8e7f/example/src/Transcribe.tsx#L112-L115

**Comment by Wali-Shajeeh** [comment]
<img width="786" alt="ss" src="https://github.com/user-attachments/assets/711d3e17-4258-4ea8-b98e-8d4a01a5208d">

Heyy I have tried many ways to give file path and I also followed your suggestion. but I can not initialize whisper and badly frustrated of this. my ggml-tiny.en.bin and small model file is in "android\app\src\assets\ggml-model-whisper-small.en.bin"
I also put this file in main project folder. I am getting error that failed to initialize whisper "can not read undefined"..
I really need help you set up this. If I need to download anyother things you can tell me. I have installed whisper library and downloaded models file

**Comment by jhen0409** [comment]
You can run our [example](https://github.com/mybigday/whisper.rn/blob/main/CONTRIBUTING.md#development-workflow) to see the different. I can't provide much helps because these only involve basic development knowledge.

**Comment by mlbrothers** [comment]
Hey @Wali-Shajeeh 
You found any solution to this? I have my file in assets folder and I cannot load it.
