### ISSUE TITLE
How do I add CoreML to whisper.rn?

### ISSUE THREAD

**Issue by arifrohmanhakim** [mybigday/whisper.rn#28]
I've added this library to my app, and I'm using the "tiny" model but it's taking too long to respond.

I found the application "HelloTranscribe" where the application is very fast in responding, and in version 2.2 it uses CoreML.

does anyone know how to make whisper.rn fast in responding? or how to configure CoreML in whisper.rn?

https://www.bjnortier.com/2023/04/13/Hello-Transcribe-v2.2.html

**Comment by jhen0409** [comment]
We don't yet support CoreML. Also, [whisper.cpp](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.3.0) just released v1.3.0 yesterday with CoreML support. I'll start working on this.

> I'm using the "tiny" model but it's taking too long to respond.

I'm a little curious what size audio file are you using, is it on Release mode? Is it wrapped as Archive? (Usually this has a big performance difference)

**Comment by illusion77** [comment]
> 
Hi bro, I still can not get right result from this lib, do you know what is the problem? [https://github.com/mybigday/whisper.rn/issues/34#issue-1685468701](url)
Many thanks!

**Comment by chen-rn** [comment]
Hey @jhen0409! Great to see that you're working on the CoreML integration :) How's that coming along? Any expected release dates?

**Comment by jhen0409** [comment]
Previously I was waiting for a feature like https://github.com/ggerganov/whisper.cpp/pull/812 (it allowed runtime switch CPU & ANE), but after that I got a little busy. I expect to have an initial version of it around this week.
