### ISSUE TITLE
Error: Failed to load the model. 

### ISSUE THREAD

**Issue by jashpaleja** [mybigday/whisper.rn#30]
I keep getting this error while I am trying to get transcribeRealtime. I am using React Native 0.71. I have followed all the steps mentioned for the installation. Below is an example of my code.
I am using this model:- [https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-base.en.bin](https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-base.en.bin)

```
  const modelPath = 'file://../assets/ggml-base.en.bin';

   const wisperTranscripts = async () => {
    const options = {language: 'en'};
    const whisperContext = await initWhisper({modelPath});
    const {stop, subscribe} = await whisperContext.transcribeRealtime(options);
    subscribe(evt => {
      const {isCapturing, data, processTime, recordingTime} = evt;
      console.log(
        `Realtime transcribing: ${isCapturing ? 'ON' : 'OFF'}\n` +
          // The inference text result from audio record:
          `Result: ${data.result}\n\n` +
          `Process time: ${processTime}ms\n` +
          `Recording time: ${recordingTime}ms`,
      );
      if (!isCapturing) console.log('Finished realtime transcribing');
    });
  };

```

Let me know is there is any update regarding the same. Or am I doing something wrong?

**Comment by jhen0409** [comment]
> const whisperContext = await initWhisper({modelPath});

The model path property is named `filePath`, and the documentation and [example](https://github.com/mybigday/whisper.rn/blob/main/example/src/App.js#L143) already make this clear.
