### ISSUE TITLE
Build failing for Android on Mac M1

### ISSUE THREAD

**Issue by fedpre** [mybigday/whisper.rn#64]
Hi,
I am getting this error when I build my project on a Mac M1:

`Execution failed for task ':whisper.rn:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using <PATH-TO-PROJECT>/node_modules/whisper.rn/android/src/main/jni/whisper/Android.mk: ERROR: Unknown host CPU architecture: arm64`

Anything you can think of to fix it? 
Thanks

**Comment by jhen0409** [comment]
Hi, can you share the build configuration of the project? Thanks!

I also got this issue where I implementing this package, but not remember the details, it probably related to NDK version.

You can also refer to [the example](https://github.com/mybigday/whisper.rn/blob/main/example/android/build.gradle).

**Comment by fedpre** [comment]
Nice mate thanks! I updated the NDK version to `24.0.8215888` and I don't have the problem anymore.

OT, can I ask you a bit more info on how to add the models locally in iOS and Android? Is there a specific folder/structure to do it? Thanks!

**Comment by jhen0409** [comment]
You can see what the example did.

- Android: It put the file in [android/app/src/main/assets](https://github.com/mybigday/whisper.rn/blob/main/scripts/bootstrap.sh#L31-L32)
- iOS: it uses [a file reference](https://github.com/mybigday/whisper.rn/blob/main/example/ios/RNWhisperExample.xcodeproj/project.pbxproj#L17) which means it will bundle it as asset

So you can use `isBundleAsset` option of initWhisper, and specify the bundle asset path.
