### ISSUE TITLE
Error occurs when running the example app for iOS

### ISSUE THREAD

**Issue by ilearnio** [mybigday/whisper.rn#75]
I am trying to run the example app, so I've installed I believe evertything necessary (I ran `yarn` and `yarn pods` in example folder and `yarn` in root folder). Then I ran `yarn example ios --configuration Release` and got the error below.

I'm on MacOS Monterey 12.5.1 (21G83) with M1 CPU.

[See this gist for error](https://gist.github.com/ilearnio/2e79659097d02e0c32f587428260e4f3)

The error doesn't give much info so I'm not sure where to debug it

**Comment by jhen0409** [comment]
Looks like you are missing to run `yarn bootstrap` in root dir. (ref: [bootstrap.sh](https://github.com/mybigday/whisper.rn/blob/main/scripts/bootstrap.sh))

In readme:

> Please follow the [Development Workflow section of contributing guide](https://github.com/mybigday/whisper.rn/blob/main/CONTRIBUTING.md#development-workflow) to run the example app.

Also, I realized the guide haven't mentioned about `yarn example pods` for iOS, I'll add it later.

**Comment by ilearnio** [comment]
@jhen0409 Thanks for the reply. I did as you suggested but it didn't resolve the error. I noticed that the error was happening because of this:

```
whisper.rn/cpp/rn-whisper.cpp:5:10: fatal error: 'whisper.h' file not found
#include "whisper.h"
         ^~~~~~~~~~~
1 error generated.
```

There were a few of these errors, like in "ios" folder I had to fix paths to `whisper.h`. But then there is this error `'FBReactNativeSpec/FBReactNativeSpec.h file not found` which happens somewhere in react-native npm package, and sadly I couldn't goodle anything about it, so I'll give up for now.

It would be good if there would be a separate example project that just imports `whisper.rn` so it's easier to add it to existing react-native apps, rather than installing this entire repo which requires complex setup

**Comment by jhen0409** [comment]
We have CI to ensure the example building passed you can refer to, it's not complicated. But I guess you haven't missing any other required setup, it might be to check another things like Xcode version, or try to clear cache.

It maybe helpful to have an another example to install the latest version of `whisper.rn` from NPM, but it just a small difference, I'll consider whether we should have it.
