### ISSUE TITLE
Getting Progress

### ISSUE THREAD

**Issue by lightninglu10** [mybigday/whisper.rn#87]
Is there a way to get the transcription progress? I see in whisper.cpp you can pass an option as --print-progress, but it doesn't seem like that's an option we can pass to transcribe here.

**Comment by jhen0409** [comment]
Yeah, we can implement `progress_callback` like the [main example](https://github.com/ggerganov/whisper.cpp/blob/a792c4079ce61358134da4c9bc589c15a03b04ad/examples/main/main.cpp#L917) does.

**Comment by lightninglu10** [comment]
Just saw you released this great feature! 

One question I have is in debug mode, it only outputs twice:

```
 LOG  0
 LOG  92
 LOG  Transcribed in 14160ms in debug mode
```

Is this normal? I was expecting it to output more frequently.

**Comment by jhen0409** [comment]
As I know, currently the progress is depends on audio time ([source](https://github.com/ggerganov/whisper.cpp/blob/a792c4079ce61358134da4c9bc589c15a03b04ad/whisper.cpp#L4209)), it obtain a chunk less than 30s to make an inference, so it usually more useful on transcribe large files. I'm not sure if we want more frequently events (like after encode or each decode run).

Also, I see that the progress 100 is not emitted as expected, I'll check it first.
