### ISSUE TITLE
Cannot run example project

### ISSUE THREAD

**Issue by bbetters** [mybigday/whisper.rn#99]
After having issues using whisper.rn in my project i tried running the example project and i get the same error:

> RNWhisperExample@0.0.1 android
> react-native run-android      

info JS server already running.
info Installing the app...
<=============> 100% CONFIGURING [1m 10s]
<=============> 100% CONFIGURING [1m 11s]
> IDLE

> Task :react-native-fs:processDebugManifest
package="com.rnfs" found in source AndroidManifest.xml: C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\react-native-fs\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.      
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace       
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :react-native-zip-archive:processDebugManifest
package="com.rnziparchive" found in source AndroidManifest.xml: C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\react-native-zip-archive\android\src\main\AndroidManifest.xml. 
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.      
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace       
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :whisper.rn:processDebugManifest
package="com.rnwhisper" found in source AndroidManifest.xml: C:\Users\eraldo\Desktop\better\whisper.rn\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.      
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace       
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :react-native-fs:compileDebugJavaWithJavac

> Task :react-native-zip-archive:compileDebugJavaWithJavac

> Task :whisper.rn:compileDebugJavaWithJavac

> Task :app:configureCMakeDebug[arm64-v8a]
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++:   CMakeLists.txt:28 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/arm64-v8a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/arm64-v8a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :app:configureCMakeDebug[armeabi-v7a]
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++:   CMakeLists.txt:28 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/armeabi-v7a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :app:configureCMakeDebug[x86]
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++:   CMakeLists.txt:28 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :app:configureCMakeDebug[x86_64]
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++:   CMakeLists.txt:28 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86_64/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86_64/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
C/C++: CMake Warning at C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/eraldo/AppData/Local/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86_64/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
C/C++:   C:/Users/eraldo/Desktop/better/whisper.rn/example/android/app/.cxx/Debug/6w31d6j3/x86_64/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :whisper.rn:configureNdkBuildDebug[arm64-v8a] FAILED
90 actionable tasks: 90 executed
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\react-native-zip-archive\android\src\main\java\com\rnziparchive\RNZipArchiveModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\eraldo\Desktop\better\whisper.rn\android\src\newarch\java\com\rnwhisper\RNWhisperModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':whisper.rn:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using C:\Users\eraldo\Desktop\better\whisper.rn\android\src\main\jni\whisper\Android.mk: C++ build system [configure] failed while executing:   
      @echo off
      "C:\\Users\\eraldo\\AppData\\Local\\Android\\Sdk\\ndk\\24.0.8215888\\ndk-build.cmd" ^    
        "NDK_PROJECT_PATH=null" ^
        "APP_BUILD_SCRIPT=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\src\\main\\jni\\whisper\\Android.mk" ^
        "NDK_APPLICATION_MK=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\src\\main\\jni\\whisper\\Application.mk" ^
        "APP_ABI=arm64-v8a" ^
        "NDK_ALL_ABIS=arm64-v8a" ^
        "NDK_DEBUG=1" ^
        "APP_PLATFORM=android-21" ^
        "NDK_OUT=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\build\\intermediates\\cxx\\Debug\\5sf1v255/obj" ^
        "NDK_LIBS_OUT=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\build\\intermediates\\cxx\\Debug\\5sf1v255/lib" ^
        "APP_SHORT_COMMANDS=false" ^
        "LOCAL_SHORT_COMMANDS=false" ^
        -B ^
        -n
    from C:\Users\eraldo\Desktop\better\whisper.rn\android
  make: *** No rule to make target 'C:/Users/eraldo/Desktop/better/whisper.rn/android/src/main/jni/whisper/../../../../../cpp/ggml.c', needed by 'C:\Users\eraldo\Desktop\better\whisper.rn\android\build\intermediates\cxx\Debug\5sf1v255/obj/local/arm64-v8a/objs-debug/whisper/C_/Users/eraldo/Desktop/better/whisper.rn/android/src/main/jni/whisper/__/__/__/__/__/cpp/ggml.o'.  Stop. 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\react-native-zip-archive\android\src\main\java\com\rnziparchive\RNZipArchiveModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\eraldo\Desktop\better\whisper.rn\android\src\newarch\java\com\rnwhisper\RNWhisperModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':whisper.rn:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using C:\Users\eraldo\Desktop\better\whisper.rn\android\src\main\jni\whisper\Android.mk: C++ build system [configure] failed while executing:   
      @echo off
      "C:\\Users\\eraldo\\AppData\\Local\\Android\\Sdk\\ndk\\24.0.8215888\\ndk-build.cmd" ^    
        "NDK_PROJECT_PATH=null" ^
        "APP_BUILD_SCRIPT=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\src\\main\\jni\\whisper\\Android.mk" ^
        "NDK_APPLICATION_MK=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\src\\main\\jni\\whisper\\Application.mk" ^
        "APP_ABI=arm64-v8a" ^
        "NDK_ALL_ABIS=arm64-v8a" ^
        "NDK_DEBUG=1" ^
        "APP_PLATFORM=android-21" ^
        "NDK_OUT=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\build\\intermediates\\cxx\\Debug\\5sf1v255/obj" ^
        "NDK_LIBS_OUT=C:\\Users\\eraldo\\Desktop\\better\\whisper.rn\\android\\build\\intermediates\\cxx\\Debug\\5sf1v255/lib" ^
        "APP_SHORT_COMMANDS=false" ^
        "LOCAL_SHORT_COMMANDS=false" ^
        -B ^
        -n
    from C:\Users\eraldo\Desktop\better\whisper.rn\android
  make: *** No rule to make target 'C:/Users/eraldo/Desktop/better/whisper.rn/android/src/main/jni/whisper/../../../../../cpp/ggml.c', needed by 'C:\Users\eraldo\Desktop\better\whisper.rn\android\build\intermediates\cxx\Debug\5sf1v255/obj/local/arm64-v8a/objs-debug/whisper/C_/Users/eraldo/Desktop/better/whisper.rn/android/src/main/jni/whisper/__/__/__/__/__/cpp/ggml.o'.  Stop. 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 13s

    at makeError (C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\execa\index.js:174:9)
    at C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\execa\index.js:278:16    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)  
    at async Command.handleAction (C:\Users\eraldo\Desktop\better\whisper.rn\example\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

**Comment by bbetters** [comment]
Managed to run following the yarn commands but there is no way i can run inside my original project

**Comment by jhen0409** [comment]
> Managed to run following the yarn commands

Yeah it should be mentioned in the readme.

> but there is no way i can run inside my original project

Feel free to open an new issue if you have more error report about this by using the npm package.
